### ISSUE TITLE
README.md markdown polluted with hidden StackEdit metadata.

### ISSUE THREAD

**Issue by ixuz** [JosefinBerndtson/M.I.I.20#2]
At the bottom of the `README.md` markup file, there is hidden metadata (seemingly introduced by the tool called StackEdit? Probably https://stackedit.io/):

```
<!--stackedit_data:
eyJoaXN0b3J5IjpbLTc5MjA5ODE3OF19
-->
```

Here's the decoded metadata (from base64 representation)

```
{"history":[-792098178]}
```

The metadata seems to be unreleated to the `README.md`, therefore I suggest removal of this metadata from the `README.md` file.

**Comment by jonassodergren** [comment]
I agree. But i suppose online publishing tools like stackedit cannot can not be used with github then.

**Comment by ixuz** [comment]
I confirm issue is resolved by your commit https://github.com/JosefinBerndtson/M.I.I.20/commit/05eab2769ee5537799c532a394d8b520c0ea7ceb 

Thank you @JosefinBerndtson

**Comment by JosefinBerndtson** [comment]
Great, thanks for your input!
