### ISSUE TITLE
(Useless) StackEdit file introduced to repository

### ISSUE THREAD

**Issue by ixuz** [JosefinBerndtson/M.I.I.20#4]
A new (useless) file has been created by @JosefinBerndtson (or autonomously by StackEdit? 🤔 )

See git commit:
https://github.com/JosefinBerndtson/M.I.I.20/commit/1d3441f53742da52c1d1a08e3342e4b42d97f544

The file (raw) contains the following lines:
```



> Written with [StackEdit](https://stackedit.io/).
<!--stackedit_data:
eyJoaXN0b3J5IjpbNzMwOTk4MTE2XX0=
-->
```

The new file renders as (StackEdit metadata is hidden/not rendered):

> Written with [StackEdit](https://stackedit.io/).

The hidden metadata decodes to (seemingly unrelated to this repository):
```
{"history":[730998116]}
```

I find this StackEdit tool quite obnoxious in the way it adds hidden metadata and sometimes even plainly visible tags, or market itself in the repositories. If the tool StackEdit can't be configured to not introduce this kind of (unwanted) data into the repository, I suggest moving to another tool, e.g. "Visual Studio Code". It will not add any hidden metadata, and also provides a preview of the Rendered markup.

# Suggested fix:

Remove this file from the repository: [M.I.I..md](https://github.com/JosefinBerndtson/M.I.I.20/blob/master/M.I.I..md)

**Comment by JosefinBerndtson** [comment]
Thanks, it is now done
